version: 0.2

phases:

  install:
    commands:
      - echo "*** codebuild environment variables ***"
      - echo "github token = $GH_TOKEN"
      - echo "npm token    = $NPM_TOKEN"

      - echo "*** codebuild node ***"
      - echo "install node 8.5.0"
      - echo "semantic-release requires node >=8.3"
      - echo "see 'https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#why-does-semantic-release-require-node-version--83'"
      - npm install -g n
      - n 8.5.0

      - echo "*** codebuild versions ***"
      - echo "node version"
      - node --version
      - echo "npm version"
      - npm --version

      - echo "install local dependancies"
      - npm install
  
  pre_build:
    commands:
      - echo "run unit tests"
      - npm run test
      
      # - echo "run package.json preperation"
      # - npm run prepare
  
  build:
    commands:
      - echo "create build"
      - npm run build

  post_build:
    commands:
      - echo "publish"
      - npm run publish
